---
- name: (RHEL) Force Yum cache refresh
  ansible.builtin.command: yum clean metadata
  when: nginx_manage_repo | bool
  changed_when: false

- name: (RHEL) {{ nginx_setup | capitalize }} NGINX
  ansible.builtin.yum:
    name: nginx{{ nginx_version | default('') }}
    state: "{{ nginx_state }}"
    update_cache: true
    allow_downgrade: "{{ omit if ansible_version['full'] is version('2.12', '<') else true }}"
  ignore_errors: "{{ ansible_check_mode }}"
  notify: (Handler) Run NGINX
